// <auto-generated />
using GarageApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarageApp.Data.Migrations
{
    [DbContext(typeof(GarageAppDbContext))]
    [Migration("20260927145403_SeedGaragesAndCars")]
    partial class SeedGaragesAndCars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GarageApp.Data.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GarageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int?>("ProductionMonth")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GarageId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GarageId = 1,
                            IsAvailable = true,
                            Make = "Toyota",
                            Model = "Corolla",
                            ProductionMonth = 5,
                            Type = 1,
                            Year = 2021
                        },
                        new
                        {
                            Id = 2,
                            GarageId = 1,
                            IsAvailable = true,
                            Make = "Volkswagen",
                            Model = "Golf",
                            ProductionMonth = 9,
                            Type = 0,
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            GarageId = 2,
                            IsAvailable = false,
                            Make = "BMW",
                            Model = "X5",
                            ProductionMonth = 2,
                            Type = 8,
                            Year = 2022
                        },
                        new
                        {
                            Id = 4,
                            GarageId = 3,
                            IsAvailable = true,
                            Make = "Ford",
                            Model = "Transit",
                            ProductionMonth = 11,
                            Type = 7,
                            Year = 2020
                        });
                });

            modelBuilder.Entity("GarageApp.Data.Models.Garage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.ToTable("Garages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Sofia, Bulgaria",
                            Name = "Auto Center Sofia"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Plovdiv, Bulgaria",
                            Name = "Plovdiv Motors"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Varna, Bulgaria",
                            Name = "Black Sea Garage"
                        });
                });

            modelBuilder.Entity("GarageApp.Data.Models.Car", b =>
                {
                    b.HasOne("GarageApp.Data.Models.Garage", "Garage")
                        .WithMany("Cars")
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("GarageApp.Data.Models.Garage", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
