// <auto-generated />
using BookShelf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookShelf.Data.Migrations
{
    [DbContext(typeof(BookShelfDbContext))]
    [Migration("20260929104935_SeedInitialBooksAndAuthorsData")]
    partial class SeedInitialBooksAndAuthorsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookShelf.Data.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "United Kingdom",
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = 2,
                            Country = "United Kingdom",
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = 3,
                            Country = "United States",
                            Name = "Mark Twain"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Russia",
                            Name = "Fyodor Dostoevsky"
                        },
                        new
                        {
                            Id = 5,
                            Country = "United States",
                            Name = "Ernest Hemingway"
                        });
                });

            modelBuilder.Entity("BookShelf.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Title = "1984",
                            Year = 1949
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Title = "Animal Farm",
                            Year = 1945
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Title = "Pride and Prejudice",
                            Year = 1813
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Title = "Sense and Sensibility",
                            Year = 1811
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Title = "The Adventures of Tom Sawyer",
                            Year = 1876
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            Title = "Adventures of Huckleberry Finn",
                            Year = 1884
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            Title = "Crime and Punishment",
                            Year = 1866
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            Title = "The Idiot",
                            Year = 1869
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 5,
                            Title = "The Old Man and the Sea",
                            Year = 1952
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            Title = "A Farewell to Arms",
                            Year = 1929
                        });
                });

            modelBuilder.Entity("BookShelf.Data.Models.Book", b =>
                {
                    b.HasOne("BookShelf.Data.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookShelf.Data.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
